---
title: "Instacart 2017 Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    navbar:
      - { title: "Home", href: "index.html", align: left }
      - { title: "Professional Experiences", href: "about.html", align: left }
      - { title: "Old website", href: "http://google.com", align: left }
      - { icon: fa-linkedin fa-lg, href: "https://www.linkedin.com/in/xiaoyue-mary-ma/", align: right }
      - { icon: fa-envelope fa-lg, href: "mailto:<xm2229@cumc.columbia.edu>", align: right }
      - { icon: fa-github fa-lg, href: "http://github.com/doubbymary", align: right }
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)
set.seed(1)

data("instacart")
instacart = instacart %>%
  select(order_dow, order_hour_of_day, department, add_to_cart_order) %>%
  filter(!is.na(order_dow),
         !is.na(order_hour_of_day)) %>%
  sample_n(6000)

popular_dep = instacart %>%
  count(department, sort = TRUE) %>%
  top_n(8) %>%
  select(department)
```

Column {data-width=650}
-----------------------------------------------------------------------

### The hour of the day and day of the week for each order in different departments

```{r}
inner_join(instacart, popular_dep, by="department") %>%
  mutate(text_label = str_c("Day of week: ", order_dow, 
                            "\nHour of day: ", order_hour_of_day)) %>%
  plot_ly(x = ~order_dow, y = ~order_hour_of_day, type = "scatter", mode = "markers",
          color = ~department, text = ~text_label, colors = "Set1", alpha = 1)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Number of orders added to the cart for selected department

```{r}
inner_join(instacart, popular_dep, by="department") %>%
  mutate(department = fct_reorder(department, add_to_cart_order)) %>%
  plot_ly(y = ~add_to_cart_order, color = ~department, type = "box", colors = "Set2")
```

### Number of items purchased within each department

```{r}
instacart %>% 
  count(department) %>% 
  mutate(department = fct_reorder(department, n)) %>% 
  plot_ly(x = ~department, y = ~n, color = ~department, type = "bar", colors = "Set3")
```

